name: Story
version: '0-1.0-SNAPSHOT'
main: com.canefe.story.Story
api-version: '1.21'
depend:
  - BetterHealthBar
softdepend:
  - PlaceholderAPI # Provides placeholders for dynamic text replacement.
  - DecentHolograms # Enables holographic displays for visual elements.
  - ItemsAdder # Adds custom items and textures to the game.
  - RealisticSeasons # Implements seasonal changes in the game world.
  - ReviveMe # Allows players to revive others in the game.
  - TheNewEconomy # Adds an economy system for managing in-game currency.
  - MythicMobs # Enables the creation of custom mobs and bosses.
  - SuperVanish
  - PremiumVanish
